// <auto-generated />
using System;
using CarparkInfo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarparkInfo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526063612_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("CarparkInfo.Domain.Entities.CarPark", b =>
                {
                    b.Property<string>("CarParkNo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("CarParkDecks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarParkTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FreeParking")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GantryHeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsBasement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NightParking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParkingSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortTermParking")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("XCoord")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("YCoord")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("CarParkNo");

                    b.HasIndex("CarParkTypeId");

                    b.HasIndex("FreeParking");

                    b.HasIndex("GantryHeight");

                    b.HasIndex("NightParking");

                    b.HasIndex("ParkingSystemId");

                    b.ToTable("CarParks");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.CarParkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CarParkTypes");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.ParkingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ParkingSystems");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.UserFavourite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarParkNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "CarParkNo");

                    b.HasIndex("CarParkNo");

                    b.ToTable("UserFavourites");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.CarPark", b =>
                {
                    b.HasOne("CarparkInfo.Domain.Entities.CarParkType", "CarParkType")
                        .WithMany("CarParks")
                        .HasForeignKey("CarParkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarparkInfo.Domain.Entities.ParkingSystem", "ParkingSystem")
                        .WithMany("CarParks")
                        .HasForeignKey("ParkingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarParkType");

                    b.Navigation("ParkingSystem");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.UserFavourite", b =>
                {
                    b.HasOne("CarparkInfo.Domain.Entities.CarPark", "CarPark")
                        .WithMany("FavouritedBy")
                        .HasForeignKey("CarParkNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarparkInfo.Domain.Entities.User", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarPark");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.CarPark", b =>
                {
                    b.Navigation("FavouritedBy");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.CarParkType", b =>
                {
                    b.Navigation("CarParks");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.ParkingSystem", b =>
                {
                    b.Navigation("CarParks");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Entities.User", b =>
                {
                    b.Navigation("Favourites");
                });
#pragma warning restore 612, 618
        }
    }
}
